module ISM

    module Default

        module CommandLine

            DebugLevel = 0
            Title = "Ingenius System Manager"
            Name = "ism"
            NeedSuperUserAccessText = "ISM need superuser access to run this command"
            ErrorUnknowArgument = "ISM error: unknow argument "
            ErrorUnknowArgumentHelp1 = "Use "
            ErrorUnknowArgumentHelp2 = "ism --help "
            ErrorUnknowArgumentHelp3 = "to know how to use ISM"
            ProcessNotificationCharacters = ">_"
            InternalErrorTitle = "Internal error"
            TaskBuildingProcessErrorText1 = "The ISM task at "
            TaskBuildingProcessErrorText2 = " encountered an error at line number "
            InstallerImplementationErrorTitle = "Software installer implementation error"
            InstallerImplementationErrorText1 = "The installer for the software "
            InstallerImplementationErrorText2 = " encountered an error at line number "
            InstallerImplementationErrorNotificationHelp = "ISM raised that error because the task cannot be compiled. That mean the related installer need to be fix."
            TaskBuildingErrorNotificationHelp = "ISM raised that error because the task cannot be compiled. That mean probably the task building process need to be fix."
            SystemCallErrorNotificationHelp = "ISM raised that error because the ran script did not call properly a system command or the system command itself need to be fix."
            DownloadText = "Downloading "
            CheckText = "Checking "
            ExtractText = "Extracting "
            PatchText = "Patching "
            LocalPatchText = "Applying local patch added by the user "
            PrepareText =  "Preparing " 
            ConfigureText = "Configuring "
            BuildText = "Building "
            PrepareInstallationText = "Preparing installation for "
            InstallText = "Installing "
            RecordNeededKernelFeaturesText = "Recording needed kernel features for "
            CleanText = "Cleaning "
            UpdateKernelOptionsDatabaseText = "Updating kernel options database for "
            RecordUnneededKernelFeaturesText = "Recording unneeded kernel features for "
            UninstallText = "Uninstalling "
            ErrorDownloadText = "Failed to download from "
            ErrorConnexionText1 = "Failed to connect to "
            ErrorConnexionText2 = ". The connexion is unaivalable"
            ErrorCheckText1 = "Failed check because the md5sum digest of "
            ErrorCheckText2 = " doesn't match with the given md5sum value "
            ErrorExtractText1 = "Failed to extract the archive located at "
            ErrorExtractText2 = " to "
            ErrorApplyPatchText = "Failed to apply the patch "
            ErrorUpdateUserFileText = "Failed to update the user file with the data: "
            ErrorUpdateGroupFileText = "Failed to update the group file with the data: "
            ErrorCopyFileText1 = "Failed to copy the file from "
            ErrorCopyFileText2 = " to "
            ErrorCopyDirectoryText1 = "Failed to copy the directory from "
            ErrorCopyDirectoryText2 = " to "
            ErrorDeleteFileText = "Failed to delete the file "
            ErrorMoveFileText1 = "Failed to move "
            ErrorMoveFileText2 = " to "
            ErrorMakeDirectoryText = "Failed to make directory "
            ErrorDeleteDirectoryText = "Failed to delete directory "
            ErrorMakeLinkUnknowTypeText1 = "Failed to make symbolic link from "
            ErrorMakeLinkUnknowTypeText2 = " to "
            ErrorMakeLinkUnknowTypeText3 = ". Unknow link type: "
            ErrorGetFileContentText = "Failed to get file content from "
            ErrorRunSystemCommandText1 = "Failed to run "
            ErrorRunSystemCommandText2 = " in "
            ErrorRunSystemCommandText3 = " with given environment "
            ErrorRunSystemCommandText4 = " with the loaded environment file "
            ErrorUpdateKernelOptionsDatabaseText = "Failed to update the option database for the kernel "
            InextricableText = "ISM stopped due to an inextricable problem of dependencies with these softwares:"
            MissingSelectedDependenciesText = "ISM stopped due to missing unique dependencies not selected yet:"
            MissingSelectionText = "One of these unique dependencies need to be selected:"
            SkippedUpdatesText = "ISM will skip some updates due to missing dependencies:"
            UnavailableText1 = "ISM stopped due to some missing dependencies for the requested softwares:"
            UnavailableText2 = " is missing for "
            NoUpdate = "System up to date."
            NoCleaningRequiredMessage = "No cleaning required. Task complete."
            CalculationTitle = "ISM start to calculate dependencies: "
            CalculationWaitingText = "Checking dependencies tree"
            SynchronizationWaitingText = "Synchronization with the online database"
            CodependencyExtensionText = "Codependency"
            CalculationDoneText = "Done !"
            Separator = "============"
            NoOptionText = "no option"
            NewText = "New!"
            AdditionalVersionText = "Additional Version"
            UpdateText = "Update"
            BuildingPhaseText = "Building Phase"
            OptionUpdateText = "Option Update"
            RebuildText = "Rebuild"
            InstallSummaryText = " new softwares will be install"
            InstallQuestion = "Would you like to install these softwares ?"
            UpdateSummaryText = " softwares will be build for the system update"
            UpdateQuestion = "Would you like to build these softwares ?"
            UninstallSummaryText = " softwares will be uninstall included unneeded dependencies"
            UninstallQuestion = "Would you like to uninstall these softwares ?"
            YesReplyOption = "y"
            NoReplyOption = "n"
            InstallingText = "Installing"
            UninstallingText = "Uninstalling"
            InstallationDetailsText = "Installation Complete"
            NewSoftwareNumberDetailText = "New software number"
            NewDirectoryNumberDetailText = "New directory number"
            NewSymlinkNumberDetailText = "New symlink number"
            NewFileNumberDetailText = "New file number"
            InstalledSizeDetailText = "Total size"
            DoesntExistText = "Some requested softwares doesn't exist. Task cancelled."
            NoMatchFound = "No match found with the database for "
            NoMatchFoundAdvice = "Maybe it's needed of refresh the database?"
            SoftwareNotInstalled = "The following requested softwares are not installed yet: "
            NotInstalledText = "Some requested softwares are not installed. Task cancelled."
            NoVersionAvailable = "Some requested versions are not available: "
            NoVersionAvailableAdvice = "Maybe it's needed of refresh the database?"
            SoftwareNeeded = "The following requested softwares are required for the system: "
            NeededText = "Some requested softwares are actually needed. Task cancelled."
            InstalledText = "is installed"
            UninstalledText = "is uninstalled"

            Options = [ ISM::Option::Help.new,
                        ISM::Option::Version.new,
                        ISM::Option::Software.new,
                        ISM::Option::Port.new,
                        ISM::Option::Settings.new,
                        ISM::Option::Debug.new]

        end

    end

end
