name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Generating ism tree
      run: mkdir /etc/ism && mkdir /var/ism
    - name: Setting rights to pass the test
      run: chown -R ubuntu:ubuntu /etc/ism && chown -R ubuntu:ubuntu /var/ism
    - name: Building ism
      run: crystal build Main.cr -o ism
    - name: Run test
      run: ./ism
